---
name: "Dependency Review"

on:
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail the action if any vulnerabilities are found
          fail-on-severity: moderate
          # Add comment to PR with review results
          comment-summary-in-pr: true
          # Allow certain licenses
          allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, Unlicense
          # Deny high-risk licenses
          deny-licenses: GPL-2.0, GPL-3.0, AGPL-1.0, AGPL-3.0
          # Custom configuration
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 120